# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET

  mock:
    image: elgalu/google_adwords_mock
    depends_on:
      - zalenium
    ports:
      - 8080:8080
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080
