apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  generateName: zalenium
  namespace: zalenium
  labels:
    app: zalenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        zalenium: hub
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccount: zalenium
      containers:
      - name: zalenium
        image: dosel/zalenium
        args:
        - start
        - '--desiredContainers'
        - '2'
        - '--screenWidth'
        - '1440'
        - '--screenHeight'
        - '810'
        - '--timeZone'
        - Australia/Canberra
        - '--seleniumImageName'
        - 'elgalu/selenium:latest'
        ports:
        - containerPort: 4444
          protocol: TCP
        env:
        - name: ZALENIUM_KUBERNETES_CPU_REQUEST
          value: 250m
        - name: ZALENIUM_KUBERNETES_CPU_LIMIT
          value: 500m
        - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
          value: 1Gi
        volumeMounts:
        - name: zalenium-videos
          mountPath: /home/seluser/videos
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
      volumes:
      - name: zalenium-videos
        persistentVolumeClaim:
          claimName: zalenium-videos
---
apiVersion: v1
kind: Service
metadata:
  name: zalenium
  namespace: zalenium
spec:
  type: NodePort
  ports:
    - name: zalenium
      protocol: TCP
      port: 4444
      targetPort: 4444
  selector:
    zalenium: hub
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: zalenium
#spec:
#  backend:
#    serviceName: zalenium
#    servicePort: 4444
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zalenium-videos
  namespace: zalenium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
