apiVersion: v1
kind: Template
metadata:
  name: zalenium
  annotations:
    "openshift.io/display-name": "Zalenium"
    "description": "Disposable Selenium Grid for use in OpenShift"
message: |-
  A Zalenium grid has been created in your project. Continue to overview to verify that it exists and start the deployment.

         Username: ${ZALENIUM_USER}
         Password: ${ZALENIUM_PASSWORD}
parameters:
  - name: "PROJECT_NAME"
    displayName: "The name of the project/namespace that zalenium is being deployed to"
    required: true
  - name: "DESIRED_CONTAINERS"
    displayName: "Number of initial containers."
    description: "This is the number of containers that should be created when Zalenium starts up."
    value: "2"
    required: false
  - name: "MAX_DOCKER_SELENIUM_CONTAINERS"
    displayName: "Maximum number of docker selenium containers."
    description: "This is the maximum number of docker selenium containers that can be running at any one time."
    value: "10"
    required: false  
  - name: "MAX_TEST_SESSIONS"
    displayName: "Max amount of tests executed per container."
    description: "This is the number of max amount of tests executed per container/pod."
    value: "4"
    required: false
  - name: "ZALENIUM_KUBERNETES_CPU_REQUEST"
    displayName: "CPU request for the Zalenium Hub."
    description: "This is the minimum amount of CPU that the Zalenium container will be allocated."
    value: "500m"
    required: true
  - name: "ZALENIUM_KUBERNETES_CPU_LIMIT"
    displayName: "CPU Limit for the Zalenium Hub."
    description: "This is the maximum amount of CPU that the Zalenium container will be allowed to use."
    value: "1000m"
    required: true
  - name: "ZALENIUM_KUBERNETES_MEMORY_REQUEST"
    displayName: "Memory request for the Zalenium Hub."
    description: "This is the minimum amount of memory that the Zalenium container will be allocated."
    value: "500Mi"
    required: true
  - name: "ZALENIUM_KUBERNETES_MEMORY_LIMIT"
    displayName: "Memory limit for the Zalenium Hub."
    description: "This is the maximum amount of memory that the Zalenium container will be allowed to use, it will be terminated if it exceeds this limit."
    value: "2Gi"
    required: true
  - name: "SELENIUM_KUBERNETES_CPU_REQUEST"
    displayName: "CPU request for the Selenium Pods."
    description: "This is the minimum amount of CPU that each selenium container will be allocated."
    value: "250m"
    required: false
  - name: "SELENIUM_KUBERNETES_CPU_LIMIT"
    displayName: "CPU Limit for the Selenium Pods."
    description: "This is the maximum amount of CPU that each selenium container will be allowed to use."
    value: "1000m"
    required: false
  - name: "SELENIUM_KUBERNETES_MEMORY_REQUEST"
    displayName: "Memory request for the Selenium Pods."
    description: "This is the minimum amount of memory that the each selenium container will be allocated."
    value: "250Mi"
    required: false
  - name: "SELENIUM_KUBERNETES_MEMORY_LIMIT"
    displayName: "Memory limit for the Selenium Pods."
    description: "This is the maximum amount of memory that the each selenium container will be allowed to use, it will be terminated if it exceeds this limit."
    value: "2Gi"
    required: false
  - name: "VOLUME_CAPACITY"
    displayName: "Volume capacity for the disk that contains the test results."
    description: "The volume is used to store all the test results, including logs and video recordings of the tests."
    value: "10Gi"
    required: true
  - name: "ZALENIUM_USER"
    displayName: "Basic auth user for Zalenium."
    description: "This username is used to authenticate towards the Selenium Hub URL (leave blank if you do not want authentication)."
    value: "zalenium"
    required: false
  - name: "ZALENIUM_PASSWORD"
    displayName: "Basic auth password for Zalenium."
    description: "This password is used to authenticate towards the Selenium Hub URL (leave blank if you do not want authentication)."
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    required: false
  - name: "SEND_ANONYMOUS_USAGE_INFO"
    displayName: "Send anonymous statistics back to Zalando."
    description: "Set to false if you do not want to send statistics back to Zalando."
    value: "true"
    required: false
  - name: "VIDEO_RECORDING_ENABLED"
    displayName: "Enable video recording during test runs"
    description: "Set to false if you do not want video recording during test runs."
    value: "true"
    required: false
  - name: "ZALENIUM_IMAGE_NAME"
    displayName: "The name of the image used for zalenium hub"
    value: "dosel/zalenium:latest"
    required: false
  - name: "SELENIUM_IMAGE_NAME"
    displayName: "The name of image for the selenium nodes"
    value: "elgalu/selenium:latest"
    required: false
labels:
  app: zalenium
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    name: zalenium
  spec:
    replicas: 1
    selector:
      app: zalenium
      role: hub
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          app: zalenium
          role: hub
      spec:
        containers:
        - args:
          - start
          env:
          - name: ZALENIUM_KUBERNETES_CPU_REQUEST
            value: ${SELENIUM_KUBERNETES_CPU_REQUEST}
          - name: ZALENIUM_KUBERNETES_CPU_LIMIT
            value: ${SELENIUM_KUBERNETES_CPU_LIMIT}
          - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
            value: ${SELENIUM_KUBERNETES_MEMORY_REQUEST}
          - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
            value: ${SELENIUM_KUBERNETES_MEMORY_LIMIT}
          - name: GRID_USER
            valueFrom:
                secretKeyRef:
                  key: zalenium-user
                  name: zalenium
          - name: GRID_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: zalenium-password
                  name: zalenium
          - name: DESIRED_CONTAINERS
            value: ${DESIRED_CONTAINERS}
          - name: MAX_DOCKER_SELENIUM_CONTAINERS
            value: ${MAX_DOCKER_SELENIUM_CONTAINERS}
          - name: MAX_TEST_SESSIONS
            value: ${MAX_TEST_SESSIONS}
          - name: SEND_ANONYMOUS_USAGE_INFO
            value: ${SEND_ANONYMOUS_USAGE_INFO}
          - name: SELENIUM_IMAGE_NAME
            value: ${SELENIUM_IMAGE_NAME}
          - name: VIDEO_RECORDING_ENABLED
            value: ${VIDEO_RECORDING_ENABLED}
          image: ${ZALENIUM_IMAGE_NAME}
          imagePullPolicy: IfNotPresent
          name: zalenium
          ports:
          - containerPort: 4444
            protocol: TCP
          resources:
            requests:
              cpu: ${ZALENIUM_KUBERNETES_CPU_REQUEST}
              memory: ${ZALENIUM_KUBERNETES_MEMORY_REQUEST}
            limits:
              cpu: ${ZALENIUM_KUBERNETES_CPU_LIMIT}
              memory: ${ZALENIUM_KUBERNETES_MEMORY_LIMIT}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/seluser/videos
              name: zalenium-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: zalenium
        serviceAccountName: zalenium
        terminationGracePeriodSeconds: 30
        volumes:
          - name: zalenium-volume
            persistentVolumeClaim:
              claimName: zalenium-pvc
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: 'true'
      haproxy.router.openshift.io/timeout: "5m"
    name: zalenium
  spec:
    to:
      kind: Service
      name: zalenium
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    name: zalenium
  spec:
    ports:
    - port: 4444
      protocol: TCP
      targetPort: 4444
    selector:
      app: zalenium
      role: hub
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: zalenium
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
      name: zalenium-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: Role
  metadata:
    name: zalenium-role
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods
    verbs:
    - create
    - delete
    - exec
    - get
    - list
    - watch
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods/exec
    verbs:
    - create
    - get
- apiVersion: v1
  kind: Secret
  metadata:
    name: zalenium
  stringData:
    zalenium-user: ${ZALENIUM_USER}
    zalenium-password: ${ZALENIUM_PASSWORD}
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: zalenium-role
  roleRef:
    name: zalenium-role
    namespace: ${PROJECT_NAME}
  subjects:
  - kind: ServiceAccount
    name: zalenium
