apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  namespace: zalenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        role: grid
    spec:
      # Added to test manually https://github.com/zalando/zalenium/issues/246
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "foo.local"
        - "bar.local"
      containers:
        - name: zalenium
          image: dosel/zalenium:latest
          args:
            - start
            - '--desiredContainers'
            - '2'
            - '--screenWidth'
            - '1440'
            - '--screenHeight'
            - '810'
            - '--seleniumImageName'
            - 'elgalu/selenium'
            - '--maxTestSessions'
            - '4'
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 500m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: OVERRIDE_WAIT_TIME
              value: 5m
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
          ports:
            - containerPort: 4444
              protocol: TCP
          volumeMounts:
            - name: zalenium-data
              mountPath: /home/seluser/videos
            - name: zalenium-mounted
              mountPath: /tmp/mounted
      volumes:
          - name: zalenium-data
            emptyDir: {}
          - name: zalenium-mounted
            emptyDir: {}
      serviceAccountName: zalenium
      serviceAccount: zalenium
