name: zalenium
version: 3.141.59
appVersion: 3.141.59
description: Chart for selenium grid
keywords:
  - qa
home: https://github.com/zalando/zalenium
sources:
  - https://github.com/zalando/zalenium
maintainers:
  - name: diemol
    email: diemol@gmail.com
engine: gotpl
