---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Zalenium - A flexible and scalable Selenium Grid."
keywords:    "docker, selenium, selenium, grid, kubernetes, saucelabs, browserstack, testingbot"
description: "Allows anyone to have a disposable, flexible, container based Selenium Grid infrastructure featuring video recording, live preview, basic auth & online/offline dashboards"
source_link: "https://github.com/zalando/zalenium"
favicon:     "zalando.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-88441352-2" ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  seashell:   '#fcfaf9'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'
  tangaroa:   '#152c43'
  manatee:    '#8993a2'
  edge_water: '#bddac8'

kramdown:
  auto_ids:  false

